# ================================================================
# Snowflake Environment Configuration for Streamlit in Snowflake
# ================================================================
# This file specifies the Python packages required for the
# PDF Processing & Image Analysis application
#
# IMPORTANT: For SiS, most packages are pre-installed.
# PDF processing is done via Snowflake UDFs, NOT in Streamlit code.
# ================================================================

name: pdf_processing_app
channels:
  - snowflake

dependencies:
  # Python version (provided by Snowflake)
  - python=3.10

# ================================================================
# NO ADDITIONAL PACKAGES REQUIRED FOR STREAMLIT APP!
# ================================================================
# The Streamlit app uses ONLY packages pre-installed in SiS:
#   - streamlit (pre-installed)
#   - snowflake-snowpark-python (pre-installed)
#   - pandas (pre-installed)
#
# PDF processing uses Snowflake Python UDFs with PyPDF2, which is
# specified in the UDF definition (setup.sql), NOT here.
# ================================================================

# ================================================================
# NOTES FOR SIS:
# ================================================================
# 1. Streamlit and snowflake-snowpark-python are pre-installed
# 2. pandas, numpy, and common data libraries are pre-installed
# 3. PyPDF2 is available in UDF runtime (specified in PACKAGES clause)
# 4. DO NOT add PyMuPDF - it's NOT available in SiS
# 5. Image analysis uses Snowflake Cortex AI (no additional packages needed)
# 6. ONLY use 'snowflake' channel - conda-forge and defaults are NOT supported
# ================================================================

